# Generated by Django 2.2.1 on 2019-05-28 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('weight', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(500)])),
                ('full_owner_name', models.CharField(max_length=100)),
                ('year_of_manufacture', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2019)])),
            ],
        ),
    ]
