CITIES = [
    ('Los Angeles', 'Los Angeles'),
    ('Chicago', 'Chicago'),
    ('Denver', 'Denver'),
    ('New York', 'New York'),
    ('San Francisco', 'San Francisco'),
    ('Las Vegas', 'Las Vegas'),
    ('Charlotte', 'Charlotte'),
    ('Orlando', 'Orlando'),
    ('Phoenix', 'Phoenix'),
    ('Miami', 'Miami'),
    ('Houston', 'Houston'),
    ('Boston', 'Boston'),
    ('Detroit', 'Detroit'),
    ('Fort Lauderdale', 'Fort Lauderdale'),
    ('Philadelphia', 'Philadelphia'),
    ('New York', 'New York'),
    ('Salt Lake City', 'Salt Lake City'),
    ('Washington, D.C.', 'Washington, D.C.'),
    ('San Diego', 'San Diego'),
    ('Tampa', 'Honolulu'),
    ('Portland', 'Portland'),
]